football_collectibles/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from main import views
from main.views import show_main, create_product, show_product, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, edit_product, delete_product, add_product_entry_ajax, edit_product_ajax

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product/', create_product, name='create_product'),
    path('product/<str:id>/', show_product, name='show_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:product_id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:product_id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('product/<uuid:id>/edit', edit_product, name='edit_product'),
    path('product/<uuid:id>/delete', delete_product, name='delete_product'),
    path('create-product-ajax', add_product_entry_ajax, name='add_product_entry_ajax'),
    path('edit-product-ajax/<uuid:id>/', views.edit_product_ajax, name='edit_product_ajax'),

]

main/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    CATEGORY_CHOICES = [
        # formatnya (value, label). Value disimpan di databse dan Label ditampilkan di form/admin
        ('jersey', 'Jersey'),
        ('scarves_banner', 'Scarves or Banners'),
        ('footballs', 'Collector Footballs'),
        ('autographed', 'Autographed Memorabilia'),
        ('second_hand', 'Second-Hand Collectible'),
        ('limited_edition', 'Limited Edition Item'),
        ('authentic_retail', 'Authentic Retail Jersey'),
        ('replica_jersey', 'Replica Jersey'),
        ('match_worn', 'Match-Worn Jersey'),
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100) #max_length ini akan divalidasi di form
    price = models.IntegerField()
    description = models.TextField()
    thumbnail = models.URLField() 
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default='jersey')
    is_featured = models.BooleanField(default=False)
    stock = models.PositiveIntegerField(default=0) #positive agar tidak ada nilai negatif
    brand = models.CharField(max_length=50, blank=True)
    release_year = models.IntegerField(blank=True, null=True) #blank=True artinya optional (tidak wajib diisi) dan null=True artinya boleh NULL di database
    size = models.CharField(max_length=3, choices=[
    ('s', 'S'),
    ('m', 'M'),
    ('l', 'L'),
    ('xl', 'XL'),
    ('xxl', 'XXL')
    ], blank=True)
    edition_type = models.CharField(max_length=20, choices=[
        ('replica', 'Replica'),
        ('limited', 'Limited Edition'),
        ('secondhand', 'Second Hand')
    ], default = 'replica')
    condition = models.CharField(max_length=20, choices=[
        ('new', 'New'),
        ('like_new', 'Like New'),
        ('good', 'Good'),
    ], default ='new')
    authenticity_certificate = models.BooleanField(default=False) 
    rarity_level = models.CharField(max_length=20, choices=[
        ('common', 'Common'),
        ('rare', 'Rare'),
        ('legendary', 'Legendary')
    ], default='common')
    
    # Method __str__ untuk mengembalikan representasi string dari objek
    def __str__(self):
        return self.name

main/forms.py
from django.forms import ModelForm
from main.models import Product
from django.utils.html import strip_tags

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description", "thumbnail", "category", "is_featured"
                  ,"stock", "brand", "release_year", "size", "edition_type", "condition", 
                  "authenticity_certificate", "rarity_level"
                ]
        
    def clean_name(self):
        name = self.cleaned_data["name"]
        return strip_tags(name)

    def clean_description(self):
        description = self.cleaned_data["description"]
        return strip_tags(description)
        

main/views.py
import datetime
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core import serializers
from django.shortcuts import render, redirect, get_object_or_404
from main.forms import ProductForm
from main.models import Product
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.html import strip_tags

# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    filter_type = request.GET.get("filter", "all")  

    if filter_type == "all":
        product_list = Product.objects.all()
    else:
        product_list = Product.objects.filter(user=request.user)
    context = {
        'nama_aplikasi' : 'Football Collectibles',
        'name': request.user.username,
        'class': 'PBP E',
        'product_list': product_list, # mengambil seluruh objek Produk yg tersimapn pd database
        'last_login': request.COOKIES.get('last_login', 'Never')
    }

    return render(request, "main.html", context)

# menghasilkan form yg dapat menambahkan data Product secara otomatis ketika data di submit dari form
def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == 'POST':
        product_entry = form.save(commit = False)
        product_entry.user = request.user
        product_entry.save()
        return redirect('main:show_main')

    context = {
        'form': form
    }

    return render(request, "create_product.html", context)

@login_required(login_url='/login')
def show_product(request, id):
    product = get_object_or_404(Product, pk=id) #untuk ambil objek Product berdasarkan pk
    # kalo ga ketemu return halaman 404

    context = {
        'product': product
    }

    return render(request, "product_detail.html", context)

def show_xml(request):
     product_list = Product.objects.all()
     xml_data = serializers.serialize("xml", product_list)
     return HttpResponse(xml_data, content_type="application/xml")
 
def show_json(request):
    product_list = Product.objects.all()
    data = [
        {
            'id': str(product.id),
            'name': product.name,
            'price': product.price,
            'description': product.description,
            'thumbnail': product.thumbnail,
            'category': product.category,
            'is_featured': product.is_featured,
            'stock': product.stock,
            'brand': product.brand,
            'release_year': product.release_year,
            'size': product.size,
            'edition_type': product.edition_type,
            'condition': product.condition,
            'authenticity_certificate': product.authenticity_certificate,
            'rarity_level': product.rarity_level,
            'user_id': product.user_id if product.user else None,
        }
        for product in product_list
    ]

    return JsonResponse(data, safe=False)

def show_xml_by_id(request, product_id):
    try: 
        product_item = Product.objects.filter(pk=product_id)
        xml_data = serializers.serialize("xml", product_item)
        return HttpResponse(xml_data, content_type="application/xml")
    except Product.DoesNotExist:
        return HttpResponse(status=404)

from django.http import JsonResponse
from django.core.exceptions import ObjectDoesNotExist

def show_json_by_id(request, product_id):
    try:
        product = Product.objects.select_related('user').get(pk=product_id)

        data = {
            'id': str(product.id),
            'name': product.name,
            'price': product.price,
            'description': product.description,
            'thumbnail': product.thumbnail,
            'category': product.category,
            'category_display': product.get_category_display(),
            'is_featured': product.is_featured,
            'stock': product.stock,
            'brand': product.brand,
            'release_year': product.release_year,
            'size': product.size,
            'edition_type': product.edition_type,
            'edition_type_display': product.get_edition_type_display(),
            'condition': product.condition,
            'condition_display': product.get_condition_display(),
            'authenticity_certificate': product.authenticity_certificate,
            'rarity_level': product.rarity_level,
            'rarity_level_display': product.get_rarity_level_display(),
            'user_id': product.user.id if product.user else None,
            'user_username': product.user.username if product.user else None,
        }

        return JsonResponse(data)

    except Product.DoesNotExist:
        return JsonResponse({'detail': 'Not found'}, status=404)

        
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
   if request.method == 'POST':
      form = AuthenticationForm(data=request.POST)

      if form.is_valid():
        user = form.get_user()
        login(request, user)
        response = HttpResponseRedirect(reverse("main:show_main"))
        response.set_cookie('last_login', str(datetime.datetime.now()))
        return response

   else:
      form = AuthenticationForm(request)
   context = {'form': form}
   return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_product(request, id):
    product = get_object_or_404(Product, pk=id)
    form = ProductForm(request.POST or None, instance=product)
    if form.is_valid() and request.method == 'POST':
        form.save()
        return redirect('main:show_main')

    context = {
        'form': form
    }

    return render(request, "edit_product.html", context)

def delete_product(request, id):
    product = get_object_or_404(Product, pk=id)
    product.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
@require_POST
def add_product_entry_ajax(request):
    # Ambil dan bersihkan data dari form
    name = strip_tags(request.POST.get("name", ""))
    price = strip_tags(request.POST.get("price", ""))
    description = strip_tags(request.POST.get("description", ""))
    thumbnail = strip_tags(request.POST.get("thumbnail", ""))
    category = strip_tags(request.POST.get("category", ""))
    brand = strip_tags(request.POST.get("brand", ""))
    release_year = strip_tags(request.POST.get("release_year", ""))
    size = strip_tags(request.POST.get("size", ""))
    edition_type = strip_tags(request.POST.get("edition_type", ""))
    condition = strip_tags(request.POST.get("condition", ""))
    rarity_level = strip_tags(request.POST.get("rarity_level", ""))

    # Checkbox handling
    is_featured = request.POST.get("is_featured") == 'on'
    authenticity_certificate = request.POST.get("authenticity_certificate") == 'on'

    # User
    user = request.user

    # Konversi angka dengan validasi aman
    try:
        price = int(price) if price else 0
        stock = int(strip_tags(request.POST.get("stock", "0")))
        release_year = int(release_year) if release_year else None
    except ValueError:
        return HttpResponse(b"Invalid numeric value", status=400)

    # Simpan ke database
    new_product = Product(
        name=name,
        price=price,
        description=description,
        thumbnail=thumbnail,
        category=category,
        is_featured=is_featured,
        stock=stock,
        brand=brand,
        release_year=release_year,
        size=size,
        edition_type=edition_type,
        condition=condition,
        authenticity_certificate=authenticity_certificate,
        rarity_level=rarity_level,
        user=user
    )

    new_product.save()

    return HttpResponse(b"CREATED", status=201)

@csrf_exempt
@require_POST
def edit_product_ajax(request, id):
    product = get_object_or_404(Product, pk=id)

    # Pastikan hanya owner yang bisa edit
    if request.user != product.user:
        return JsonResponse({'error': 'Unauthorized'}, status=403)

    # Bersihkan input dari form
    name = strip_tags(request.POST.get("name", product.name))
    price = strip_tags(request.POST.get("price", product.price))
    description = strip_tags(request.POST.get("description", product.description))
    thumbnail = strip_tags(request.POST.get("thumbnail", product.thumbnail))
    category = strip_tags(request.POST.get("category", product.category))
    brand = strip_tags(request.POST.get("brand", product.brand))
    release_year = strip_tags(request.POST.get("release_year", product.release_year))
    size = strip_tags(request.POST.get("size", product.size))
    edition_type = strip_tags(request.POST.get("edition_type", product.edition_type))
    condition = strip_tags(request.POST.get("condition", product.condition))
    rarity_level = strip_tags(request.POST.get("rarity_level", product.rarity_level))

    # Checkbox handling
    is_featured = request.POST.get("is_featured") == 'on'
    authenticity_certificate = request.POST.get("authenticity_certificate") == 'on'

    try:
        price = int(price)
        stock = int(strip_tags(request.POST.get("stock", product.stock)))
        release_year = int(release_year) if release_year else None
    except ValueError:
        return JsonResponse({'error': 'Invalid numeric value'}, status=400)

main/templates/card_product.html
{% load static %}

<article class="bg-white rounded-lg border border-gray-200 hover:shadow-lg transition-shadow duration-300 overflow-hidden flex flex-col">
  <!-- Thumbnail -->
  <div class="aspect-[16/9] relative overflow-hidden">
    {% if product.thumbnail %}
      <img src="{{ product.thumbnail }}" alt="{{ product.name }}" class="w-full h-full object-cover">
    {% else %}
      <div class="w-full h-full bg-gray-200"></div>
    {% endif %}

    <!-- Category Badge -->
    <div class="absolute top-3 left-3">
      <span class="inline-flex items-center px-2.5 py-0.5 rounded-md text-xs font-medium bg-russet text-white">
        {{ product.get_category_display }}
      </span>
    </div>

    <!-- Status Badges -->
    <div class="absolute top-3 right-3 flex space-x-2">
      {% if product.is_featured %}
        <span class="inline-flex items-center px-2 py-1 rounded text-xs font-medium bg-yellow-100 text-yellow-800">
          Featured
        </span>
      {% endif %}
    </div>
  </div>

  <!-- Content -->
  <div class="p-5 flex flex-col flex-1">
    <!-- Nama -->
    <h3 class="text-lg font-semibold text-gray-900 mb-2 line-clamp-2 leading-tight">
      <a href="{% url 'main:show_product' product.id %}" class="hover:text-dark-blue-900 transition-colors">
        {{ product.name }}
      </a>
    </h3>

    <!-- Price -->
    <p class="text-sm font-medium text-gray-800 mb-2">
      Rp {{ product.price }}
    </p>

    <!-- Description -->
    <p class="text-gray-600 text-sm leading-relaxed line-clamp-3 mb-2">
      {{ product.description|truncatewords:20 }}
    </p>

    <div class="mt-auto">
    <!-- Extra info as badges -->
    <div class="flex flex-wrap gap-2 mb-3">
      <span class="inline-flex items-center px-2.5 py-0.5 rounded-md text-xs font-medium bg-green-100 text-weldon-blue-800">
        {{ product.get_edition_type_display }}
      </span>
      <span class="inline-flex items-center px-2.5 py-0.5 rounded-md text-xs font-medium bg-amber-100 text-amber-800">
        {{ product.get_condition_display }}
      </span>
      <span class="inline-flex items-center px-2.5 py-0.5 rounded-md text-xs font-medium bg-yellow-100 text-yellow-800">
        Certificate: {{ product.authenticity_certificate|yesno:"Yes,No" }}
      </span>
      <span class="inline-flex items-center px-2.5 py-0.5 rounded-md text-xs font-medium bg-gray-100 text-gray-800">
        {{ product.get_rarity_level_display }}
      </span>
    </div>

    <!-- Action Buttons -->
    {% if user.is_authenticated and product.user == user %}
      <div class="flex items-center justify-between pt-3 border-t border-gray-100">
        <a href="{% url 'main:show_product' product.id %}" class="text-weldon-blue hover:text-red-600 font-medium text-sm transition-colors">
          Read more
        </a>
        <div class="flex space-x-2">
          <a href="{% url 'main:edit_product' product.id %}" class="text-gray-600 hover:text-gray-700 text-sm transition-colors">
            Edit
          </a>
          <a href="{% url 'main:delete_product' product.id %}" class="text-red-600 hover:text-red-700 text-sm transition-colors">
            Delete
          </a>
        </div>
      </div>
    {% else %}
      <div class="pt-3 border-t border-gray-100">
        <a href="{% url 'main:show_product' product.id %}" class="text-weldon-blue hover:text-red-600 font-medium text-sm transition-colors">
          Read more →
        </a>
      </div>
    {% endif %}
  </div>
</div>
</article>

main/templates/create_product.html
{% extends 'base.html' %} 
{% block content %}
<h1>Add Product</h1>

<form method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
    <tr>
      <td></td>
      <td>
        <input type="submit" value="Add PRODUCT" />
      </td>
    </tr>
  </table>
</form>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login - Football Collectibles</title>
{% endblock meta %}

{% block content %}
<div class="bg-[#D5C1AC] w-full min-h-screen flex items-center justify-center p-8">
  <div class="max-w-md w-full">
    <div class="bg-white rounded-lg border border-[#95B0BF] p-6 sm:p-8">
      <div class="text-center mb-8">
        <h1 class="text-2xl font-bold text-[#33322B] mb-2">Sign In</h1>
        <p class="text-[#7097A6]">Welcome back to Football Collectibles</p>
      </div>

      <!-- Form Errors Display -->
      {% if form.non_field_errors %}
        <div class="mb-6">
          {% for error in form.non_field_errors %}
            <div class="px-4 py-3 rounded-md text-sm border bg-red-50 border-red-200 text-red-700">
              {{ error }}
            </div>
          {% endfor %}
        </div>
      {% endif %}

      {% if form.errors %}
        <div class="mb-6">
          {% for field, errors in form.errors.items %}
            {% if field != '__all__' %}
              {% for error in errors %}
                <div class="px-4 py-3 rounded-md text-sm border bg-red-50 border-red-200 text-red-700 mb-2">
                  <strong>{{ field|title }}:</strong> {{ error }}
                </div>
              {% endfor %}
            {% endif %}
          {% endfor %}
        </div>
      {% endif %}

      <form method="POST" action="" class="space-y-6">
        {% csrf_token %}
        
        <div>
          <label for="username" class="block text-sm font-medium text-[#33322B] mb-2">Username</label>
          <input 
            id="username" 
            name="username" 
            type="text" 
            required 
            class="w-full px-4 py-3 border border-[#95B0BF] rounded-md focus:outline-none focus:border-[#7F4721] transition-colors" 
            placeholder="Enter your username">
        </div>

        <div>
          <label for="password" class="block text-sm font-medium text-[#33322B] mb-2">Password</label>
          <input 
            id="password" 
            name="password" 
            type="password" 
            required 
            class="w-full px-4 py-3 border border-[#95B0BF] rounded-md focus:outline-none focus:border-[#7F4721] transition-colors" 
            placeholder="Enter your password">
        </div>

        <button 
          type="submit" 
          class="w-full bg-[#7F4721] text-white font-medium py-3 px-4 rounded-md hover:bg-[#7097A6] transition-colors">
          Sign In
        </button>
      </form>

      <!-- Messages Display -->
      {% if messages %}
        <div class="mt-6">
          {% for message in messages %}
            <div 
              class="
                px-4 py-3 rounded-md text-sm border
                {% if message.tags == 'success' %}
                  bg-green-50 border-green-200 text-green-700
                {% elif message.tags == 'error' %}
                  bg-red-50 border-red-200 text-red-700
                {% else %}
                  bg-gray-50 border-gray-200 text-gray-700
                {% endif %}
              ">
              {{ message }}
            </div>
          {% endfor %}
        </div>
      {% endif %}

      <div class="mt-6 text-center pt-6 border-t border-[#95B0BF]">
        <p class="text-[#33322B] text-sm">
          Don't have an account? 
          <a href="{% url 'main:register' %}" class="text-[#7F4721] hover:text-[#7097A6] font-medium">
            Register Now
          </a>
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

main/templates/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="bg-gray-50 min-h-screen w-full">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">

    <!-- Back Button -->
    <p class="mb-6">
      <a href="{% url 'main:show_main' %}" 
         class="text-russet hover:underline font-medium flex items-center space-x-2">
        ← <span class="ml-2">Back to Product List</span>
      </a>
    </p>

    <!-- Loading State -->
    <div id="loading-state" class="bg-white rounded-lg border border-gray-200 p-12 text-center">
      <svg class="animate-spin h-8 w-8 text-russet inline-block" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z"></path>
      </svg>
      <p class="text-gray-600 mt-3">Loading product detail...</p>
    </div>

    <!-- Error State -->
    <div id="error-state" class="bg-white rounded-lg border border-gray-200 p-12 text-center hidden">
      <div class="text-5xl mb-4">⚠️</div>
      <h3 class="text-lg font-medium text-gray-900 mb-2">Failed to load product</h3>
      <p class="text-gray-500">Please try again later.</p>
    </div>

    <!-- Product Content (Loaded via AJAX) -->
    <div id="product-content" class="hidden">
      <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
        
        <!-- Product Image -->
        <div class="flex justify-center items-start">
          <img id="product-thumbnail" src="" alt="" class="rounded-xl shadow-md w-full max-w-md object-contain">
        </div>

        <!-- Product Details -->
        <div class="flex flex-col space-y-6 overflow-y-auto">

          <!-- Header Section -->
          <div>
            <p id="product-category" class="text-sm uppercase tracking-wide text-weldon-blue font-semibold"></p>
            <h1 id="product-name" class="text-3xl font-bold text-gray-900"></h1>
            <span id="product-featured" class="hidden inline-block mt-2 bg-dark-vanilla text-white px-3 py-1 rounded-md text-sm font-medium">
              Featured
            </span>
          </div>

          <!-- Price -->
          <div>
            <p id="product-price" class="inline-block bg-russet text-white px-5 py-3 rounded-xl text-xl font-semibold"></p>
          </div>

          <!-- Brand & Seller Box -->
          <div class="bg-dark-vanilla rounded-lg p-4 flex justify-between text-gray-800">
            <div><b>Brand:</b> <span id="product-brand"></span></div>
            <div><b>Seller:</b> <span id="product-seller"></span></div>
          </div>

          <!-- Attributes -->
          <div class="border-t border-gray-300 pt-4 grid grid-cols-2 gap-y-3 gap-x-6 text-gray-700">

            <div class="flex items-center space-x-2">
              <img src="{% static 'icons/edition.svg' %}" class="w-5 h-5">
              <span><b>Edition:</b> <span id="product-edition"></span></span>
            </div>

            <div class="flex items-center space-x-2">
              <img src="{% static 'icons/condition.svg' %}" class="w-5 h-5">
              <span><b>Condition:</b> <span id="product-condition"></span></span>
            </div>

            <div class="flex items-center space-x-2">
              <img src="{% static 'icons/rarity.svg' %}" class="w-5 h-5">
              <span><b>Rarity:</b> <span id="product-rarity"></span></span>
            </div>

            <div class="flex items-center space-x-2">
              <img src="{% static 'icons/certificate.svg' %}" class="w-5 h-5">
              <span><b>Authenticity:</b> <span id="product-authenticity"></span></span>
            </div>

            <div class="flex items-center space-x-2">
              <img src="{% static 'icons/size.svg' %}" class="w-5 h-5">
              <span><b>Size:</b> <span id="product-size"></span></span>
            </div>

            <div class="flex items-center space-x-2">
              <img src="{% static 'icons/stock.svg' %}" class="w-5 h-5">
              <span><b>Stock:</b> <span id="product-stock"></span></span>
            </div>

            <div class="flex items-center space-x-2">
              <img src="{% static 'icons/calendar.svg' %}" class="w-5 h-5">
              <span><b>Release Year:</b> <span id="product-release-year"></span></span>
            </div>
          </div>

          <!-- Description -->
          <div>
            <h2 class="text-lg font-bold text-gray-900 mb-2">Description</h2>
            <p id="product-description" class="text-gray-700"></p>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

<script>

const PRODUCT_ID = "{{ product.id }}";
const PRODUCT_DETAIL_ENDPOINT = `{% url 'main:show_json_by_id' '00000000-0000-0000-0000-000000000000' %}`.replace(
  '00000000-0000-0000-0000-000000000000',
  PRODUCT_ID
);

// DOM Elements
const loadingState = document.getElementById('loading-state');
const errorState = document.getElementById('error-state');
const productContent = document.getElementById('product-content');

const productThumbnail = document.getElementById('product-thumbnail');
const productName = document.getElementById('product-name');
const productCategory = document.getElementById('product-category');
const productPrice = document.getElementById('product-price');
const productBrand = document.getElementById('product-brand');
const productSeller = document.getElementById('product-seller');
const productEdition = document.getElementById('product-edition');
const productCondition = document.getElementById('product-condition');
const productRarity = document.getElementById('product-rarity');
const productAuthenticity = document.getElementById('product-authenticity');
const productSize = document.getElementById('product-size');
const productStock = document.getElementById('product-stock');
const productReleaseYear = document.getElementById('product-release-year');
const productDescription = document.getElementById('product-description');
const productFeatured = document.getElementById('product-featured');

// Show/hide state
function showState(state) {
  loadingState.classList.toggle('hidden', state !== 'loading');
  errorState.classList.toggle('hidden', state !== 'error');
  productContent.classList.toggle('hidden', state !== 'ready');
}

// Get readable category label
function getCategoryLabel(categoryCode) {
  const categoryMapping = {
    jersey: 'Jersey',
    scarves_banner: 'Scarves or Banners',
    footballs: 'Collector Footballs',
    autographed: 'Autographed Memorabilia',
    second_hand: 'Second-Hand Collectible',
    limited_edition: 'Limited Edition Item',
    authentic_retail: 'Authentic Retail Jersey',
    replica_jersey: 'Replica Jersey',
    match_worn: 'Match-Worn Jersey'
  };
  return categoryMapping[categoryCode] || categoryCode;
}

// Render product details
function renderProduct(product) {
  document.title = `${product.name} - Product Detail`;

  // Thumbnail
  if (product.thumbnail) {
    productThumbnail.src = product.thumbnail;
    productThumbnail.alt = product.name;
  } else {
    productThumbnail.src = "{% static 'img/no-image.png' %}";
  }

  // Basic info
  productName.textContent = product.name;
  productCategory.textContent = getCategoryLabel(product.category);
  productPrice.textContent = `Rp ${product.price.toLocaleString()}`;
  productBrand.textContent = product.brand || 'Unknown';
  productSeller.textContent = product.user_username || 'Anonymous';

  // Attributes
  productEdition.textContent = product.edition_type;
  productCondition.textContent = product.condition;
  productRarity.textContent = product.rarity_level;
  productAuthenticity.textContent = product.authenticity_certificate ? 'Available' : 'Not Available';
  productSize.textContent = product.size || '-';
  productStock.textContent = product.stock;
  productReleaseYear.textContent = product.release_year || '-';
  productDescription.textContent = product.description;

  // Featured badge
  if (product.is_featured) {
    productFeatured.classList.remove('hidden');
  }
}

async function loadProductDetail() {
  try {
    showState('loading');

    const response = await fetch(PRODUCT_DETAIL_ENDPOINT, {
      headers: { 'Accept': 'application/json' },
    });

    if (!response.ok) {
      throw new Error('Failed to fetch product detail');
    }

    const productData = await response.json();
    renderProduct(productData);
    showState('ready');
  } catch (error) {
    console.error('Error loading product detail:', error);
    showState('error');
  }
}

// Initialize page
loadProductDetail();
</script>

{% endblock content %}